<?php
$data = array (
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '耗材配件',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '15',
    'name' => '耗材配件',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => '定氮仪',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => '定氮仪',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '色谱柱',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '52',
    'name' => '色谱柱',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '气相色谱柱',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '112',
    'name' => '气相色谱柱',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '液相色谱柱',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 2,
    'id' => '113',
    'name' => '液相色谱柱',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '生命科学',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '11',
    'name' => '生命科学',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '生化分子生物',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '40',
    'name' => '生化分子生物',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => 'PCR仪',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '81',
    'name' => 'PCR仪',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '生物工程设备',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '41',
    'name' => '生物工程设备',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '摇床',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '82',
    'name' => '摇床',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => '培养箱',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '83',
    'name' => '培养箱',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '液氮罐',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '84',
    'name' => '液氮罐',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => '电泳成像',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '80',
    'name' => '电泳成像',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '计量仪器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '25',
    'name' => '计量仪器',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '天平衡器',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '31',
    'name' => '天平衡器',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '天平',
    'measure_unit' => '',
    'parent_id' => '31',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '59',
    'name' => '天平',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '温度计量仪器',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '温度计量仪器',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '温度计',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '60',
    'name' => '温度计',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => '红外测温仪',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '61',
    'name' => '红外测温仪',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '实验室仪器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 0,
    'id' => '30',
    'name' => '实验室仪器',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => '泵',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '49',
    'name' => '泵',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '蠕动泵',
    'measure_unit' => '',
    'parent_id' => '49',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '104',
    'name' => '蠕动泵',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '真空泵',
    'measure_unit' => '',
    'parent_id' => '49',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '105',
    'name' => '真空泵',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => '混合分散设备',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '46',
    'name' => '混合分散设备',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '搅拌器',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '94',
    'name' => '搅拌器',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '分散机',
    'measure_unit' => '',
    'parent_id' => '46',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '95',
    'name' => '分散机',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '制样消解设备',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '43',
    'name' => '制样消解设备',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => '微波消解器',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '90',
    'name' => '微波消解器',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '液体处理设备',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '50',
    'name' => '液体处理设备',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => '瓶口分配器',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '107',
    'name' => '瓶口分配器',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '移液器',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '106',
    'name' => '移液器',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => '恒温加热干燥设备',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '47',
    'name' => '恒温加热干燥设备',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '恒温恒湿箱',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '100',
    'name' => '恒温恒湿箱',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '马弗炉',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '97',
    'name' => '马弗炉',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => '真空干燥箱',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '101',
    'name' => '真空干燥箱',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '水浴/油浴',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '98',
    'name' => '水浴/油浴',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '加热板',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '102',
    'name' => '加热板',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '通用烘箱',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '99',
    'name' => '通用烘箱',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => '鼓风干燥箱',
    'measure_unit' => '',
    'parent_id' => '47',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '96',
    'name' => '鼓风干燥箱',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => '分离萃取设备',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '44',
    'name' => '分离萃取设备',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '离心机',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '91',
    'name' => '离心机',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => '气体发生器',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '51',
    'name' => '气体发生器',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '空气发生器',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '110',
    'name' => '空气发生器',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '氮氢空一体机',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '111',
    'name' => '氮氢空一体机',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => '氢气发生器',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '108',
    'name' => '氢气发生器',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '氮气发生器',
    'measure_unit' => '',
    'parent_id' => '51',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '109',
    'name' => '氮气发生器',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '粉碎设备',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '48',
    'name' => '粉碎设备',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '研磨机',
    'measure_unit' => '',
    'parent_id' => '48',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '103',
    'name' => '研磨机',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '纯化设备',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '45',
    'name' => '纯化设备',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '纯水器',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '92',
    'name' => '纯水器',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '旋转蒸发仪',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '93',
    'name' => '旋转蒸发仪',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '清洗消毒设备',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '42',
    'name' => '清洗消毒设备',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '电泳槽',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '85',
    'name' => '电泳槽',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '高压灭菌器',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '88',
    'name' => '高压灭菌器',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '电泳仪电源',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '86',
    'name' => '电泳仪电源',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '洗瓶机',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '89',
    'name' => '洗瓶机',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '超声波清洗器',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '87',
    'name' => '超声波清洗器',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '物性测试仪器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '32',
    'name' => '物性测试仪器',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '流变仪',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '35',
    'name' => '流变仪',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => '流变仪',
    'measure_unit' => '',
    'parent_id' => '35',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '68',
    'name' => '流变仪',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => '粘度计',
    'measure_unit' => '',
    'parent_id' => '35',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '69',
    'name' => '粘度计',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '热分析仪器',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '34',
    'name' => '热分析仪器',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '熔点仪',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '66',
    'name' => '熔点仪',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => '差式扫描量热仪',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '64',
    'name' => '差式扫描量热仪',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => '滴点软化点仪',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '67',
    'name' => '滴点软化点仪',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => '热重分析仪',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '65',
    'name' => '热重分析仪',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '环境试验箱',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '36',
    'name' => '环境试验箱',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => '高低温试验箱',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '70',
    'name' => '高低温试验箱',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '粒度仪',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '粒度仪',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '粒度仪',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '62',
    'name' => '粒度仪',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => '颗粒计数器',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '63',
    'name' => '颗粒计数器',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '37',
    'name' => '其他',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '密度计',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '71',
    'name' => '密度计',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => '温湿度计',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '72',
    'name' => '温湿度计',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '分析仪器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '分析仪器',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '质谱',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '4',
    'name' => '质谱',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '等离子体质谱',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '26',
    'name' => '等离子体质谱',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '气质联用',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '24',
    'name' => '气质联用',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '液质联用',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '8',
    'name' => '液质联用',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '电化学仪器',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => '1',
    'level' => 1,
    'id' => '5',
    'name' => '电化学仪器',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '电导率仪',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '12',
    'name' => '电导率仪',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => 'PH计',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '27',
    'name' => 'PH计',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '电位滴定',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '28',
    'name' => '电位滴定',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '卡氏水分测定',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '29',
    'name' => '卡氏水分测定',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '色谱',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '1',
    'level' => 1,
    'id' => '2',
    'name' => '色谱',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '顶空进样器',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '20',
    'name' => '顶空进样器',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '液相色谱',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '17',
    'name' => '液相色谱',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '气相色谱',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '16',
    'name' => '气相色谱',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '离子色谱',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '18',
    'name' => '离子色谱',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '自动进样器',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '19',
    'name' => '自动进样器',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '元素分析仪',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '元素分析仪',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '光谱',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '3',
    'name' => '光谱',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '原子吸收光谱',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '23',
    'name' => '原子吸收光谱',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '分光光度计',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '21',
    'name' => '分光光度计',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '红外光谱',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '13',
    'name' => '红外光谱',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '行业专用仪器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '22',
    'name' => '行业专用仪器',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '农业和食品专用仪器',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '54',
    'name' => '农业和食品专用仪器',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => 'ATP荧光检测仪',
    'measure_unit' => '',
    'parent_id' => '54',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '115',
    'name' => 'ATP荧光检测仪',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '药物检测仪器',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '53',
    'name' => '药物检测仪器',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '溶出度仪',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '114',
    'name' => '溶出度仪',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '环境监测仪器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '10',
    'name' => '环境监测仪器',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '水质分析仪',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '38',
    'name' => '水质分析仪',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => 'BOD测定仪',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '74',
    'name' => 'BOD测定仪',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '溶解氧测定仪',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '75',
    'name' => '溶解氧测定仪',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => 'TOC',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '76',
    'name' => 'TOC',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => 'COD测定仪',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '73',
    'name' => 'COD测定仪',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '气体检测仪',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '39',
    'name' => '气体检测仪',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => '烟气分析仪',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '77',
    'name' => '烟气分析仪',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => '气体采样器',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '78',
    'name' => '气体采样器',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '烟气采样器',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '79',
    'name' => '烟气采样器',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '光学仪器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '光学仪器',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '光学测量仪',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '光学测量仪',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => '折光仪',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '56',
    'name' => '折光仪',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '旋光仪',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '57',
    'name' => '旋光仪',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => '色差仪',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '58',
    'name' => '色差仪',
  ),
);
?>